name: Blank Issue Trigger
on:
  issues:
    types: [opened]
 
jobs:
  extract-fields-for-input:
    runs-on: windows-latest
    outputs:
      eventId: ${{ steps.extract.outputs.eventId }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Extract issue details using PowerShell
        id: extract
        shell: pwsh
        run: |
          # Write-Output "Extracting fields from issue body..."
          $inputString = @"
          ${{ github.event.issue.body }}
          "@
 
          $inputString -match 'EventId: "(.*?)"' | Out-Null
          $eventId = $matches[0].Replace("EventId: ", "")
          Write-Output $eventId
 
          echo "eventId=$eventId" >> $env:GITHUB_OUTPUT
 
  write-inputs-in-sharepoint:
    runs-on: windows-latest
    needs: extract-fields-for-input
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Extract issue body
        id: extract_body
        run: echo "${{ github.event.issue.body }}" > issue_body.txt
 
      - name: Run Tosca Execution Client
        run: |
          $eventId = '${{ needs.extract-fields-for-input.outputs.eventId }}'
          Write-Host "[$eventId]"
          Write-Host '[$eventId]'
          Write-Host '["$eventId"]'
 
  close-issue:
    runs-on: ubuntu-latest
    needs: write-inputs-in-sharepoint
    permissions:
      issues: write
 
    steps:
      - name: Close
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.issue.number }}
        run: gh issue close --repo "$REPO" --comment "Autoclosing issue $ISSUE" "$ISSUE"
