name: Install Python and Git on Self-Hosted Windows Runner

on:
  workflow_dispatch:

jobs:
  setup-environment:
    runs-on: self-hosted

    steps:
      - name: Print USERPROFILE
        shell: powershell
        run: echo "User profile path= $env:USERPROFILE"

      - name: Define install paths
        shell: powershell
        run: |
          echo "PYTHON_INSTALL_DIR=$env:USERPROFILE\AppData\Local\Programs\Python385" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "GIT_INSTALLER_URL=https://github.com/git-for-windows/git/releases/download/v2.46.0.windows.1/Git-2.46.0-64-bit.exe" | Out-File -FilePath $env:GITHUB_ENV -Append

      ##############################################
      ## Install Python 3.8.5
      ##############################################
      - name: Download Python 3.8.5 Installer
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.8.5/python-3.8.5-amd64.exe" -OutFile "python-3.8.5.exe"

      - name: Install Python to Custom Folder
        shell: powershell
        run: |
          $installer = "$PWD\python-3.8.5.exe"
          & $installer /quiet InstallAllUsers=0 Include_pip=1 TargetDir="$env:USERPROFILE\AppData\Local\Programs\Python385"

      - name: Add Python to user PATH (non-destructive)
        shell: powershell
        run: |
          $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
          $pythonPath = "$env:USERPROFILE\AppData\Local\Programs\Python385"
          $scriptsPath = "$pythonPath\Scripts"

          if ($userPath -notlike "*$pythonPath*") {
            $newPath = "$userPath;$pythonPath;$scriptsPath"
            [Environment]::SetEnvironmentVariable("Path", $newPath, "User")
            Write-Output "Updated user PATH with Python directories."
          } else {
            Write-Output "Python directories already exist in PATH."
          }

      - name: Verify Python installation
        shell: powershell
        run: |
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "User")
          & "$env:USERPROFILE\AppData\Local\Programs\Python385\python.exe" --version

      ##############################################
      ## Install Git 2.46.0.windows.1
      ##############################################
      - name: Download Git Installer
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "$env:GIT_INSTALLER_URL" -OutFile "git-installer.exe"

      - name: Install Git Silently
        shell: powershell
        run: |
          $installer = "$PWD\git-installer.exe"
          & $installer /SILENT

      - name: Verify Git installation
        shell: powershell
        run: |
          & git --version

      ##############################################
      ## Clone Repository to Documents
      ##############################################
      - name: Clone Repository to Documents Folder
        shell: powershell
        run: |
          $repoURL = "https://github.com/MukeshMuki18/SampleGithubActions.git"  # Change this to your repo
          $clonePath = "$env:USERPROFILE\Documents\git-repo"
          if (!(Test-Path $clonePath)) {
            git clone $repoURL $clonePath
            Write-Output "Cloned to $clonePath"
          } else {
            Write-Output "Repo already exists in Documents folder."
          }
