name: Auto Close Issue on Success

on:
#   issues:
#     types: [opened]  # Triggers when a new issue is opened

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display Issue Information
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Opened by: ${{ github.event.issue.user.login }}"

      - name: Close the issue if workflow succeeds
        run: |
          gh issue close ${{ github.event.issue.number }} --reason completed --comment "This issue has been resolved automatically."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
