name: Multiple Execution

on:
   issues:
     types: [opened]

jobs:
  identify-template:
    runs-on: windows-latest
    outputs:
      template_name: ${{ steps.identify.outputs.template_name }}
    steps:
      - name: Identify Issue Template
        id: identify
        shell: pwsh
        run: |
          $issue_title = "${{ github.event.issue.title }}"
          $issue_name = "${{ github.event.issue.name }}"
          # Define known templates
          if ($issue_title -match "\[POS API Input\]") {
              $template = "POS_API_INPUT"
          }
          elseif ($issue_title -match "\[User Registration\]") {
              $template = "USER_REGISTRATION"
          }
          elseif ($issue_title -match "\[Feature Request\]") {
              $template = "FEATURE_REQUEST"
          }
          else {
              $template = "UNKNOWN"
          }

          Write-Output "Detected template: $template"
          Write-Output "Issue Name: $issue_name"
          # Correctly set output for GitHub Actions
          echo "template_name=$template" >> $env:GITHUB_OUTPUT
  process-pos-api-input:
    runs-on: windows-latest
    needs: identify-template
    
    steps:
    - name: Extract POS API Input fields
      if: needs.identify-template.outputs.template_name == 'POS_API_INPUT'
      run: |
        echo "Processing POS API Input Template..."
    - name: Extract user registration inputs
      if: needs.identify-template.outputs.template_name == 'USER_REGISTRATION'
      run: |
        echo "Processing user registeration Template..."
        
