name: Multiple Execution

on:
  issues:
    types: [opened]

jobs:
  identify-template:
    runs-on: ubuntu-latest
    outputs:
      template_name: ${{ steps.extract-template.outputs.template_name }}
    steps:
      - name: Extract Issue Template Name
        id: extract-template
        run: |
          TEMPLATE_NAME="UNKNOWN"
          LABELS=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[].name')
          
          for label in $LABELS; do
            if [[ "$label" == "pos-api-input" ]]; then
              TEMPLATE_NAME="POS_API_INPUT"
            elif [[ "$label" == "bug-report" ]]; then
              TEMPLATE_NAME="BUG_REPORT"
            elif [[ "$label" == "feature-request" ]]; then
              TEMPLATE_NAME="FEATURE_REQUEST"
            fi
          done
          
          echo "Detected template: $TEMPLATE_NAME"
          echo "template_name=$TEMPLATE_NAME" >> "$GITHUB_OUTPUT"

  process-pos-api-input:
    runs-on: ubuntu-latest
    needs: identify-template
    if: needs.identify-template.outputs.template_name == 'POS_API_INPUT'
    steps:
      - name: Extract POS API Input fields
        run: |
          echo "Processing POS API Input Template..."

  process-bug-report:
    runs-on: ubuntu-latest
    needs: identify-template
    if: needs.identify-template.outputs.template_name == 'BUG_REPORT'
    steps:
      - name: Process Bug Report
        run: |
          echo "Processing Bug Report Template..."

  process-feature-request:
    runs-on: ubuntu-latest
    needs: identify-template
    if: needs.identify-template.outputs.template_name == 'FEATURE_REQUEST'
    steps:
      - name: Process Feature Request
        run: |
          echo "Processing Feature Request Template..."
