name: Close POS API Issue with Details

on:
  issues:
    types: [opened]

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Data File
        run: |
          echo "Season=${{ github.event.issue.body }}" > issue_data.txt
          echo "Department=${{ github.event.issue.body }}" >> issue_data.txt
          echo "ArticleCount=${{ github.event.issue.body }}" >> issue_data.txt
          echo "Promotion=${{ github.event.issue.body }}" >> issue_data.txt

      - name: Extract and Print Issue Fields using PowerShell
        shell: pwsh
        run: |
          $content = Get-Content issue_data.txt
          foreach ($line in $content) {
            if ($line -match '^(\w+)=(.*)$') {
              $key = $matches[1]
              $value = $matches[2]
              Write-Output "${key}: ${value}"
            }
          }

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "This POS API input issue has been automatically processed and closed by a GitHub Actions workflow."
