name: Close POS API Issue with Details

on:
  issues:
    types: [opened]

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Data File
        run: |
          echo "${{ toJson(github.event.issue) }}" > issue_data.json

      - name: Extract and Print Issue Fields using PowerShell
        shell: pwsh
        run: |
          $json = Get-Content issue_data.json | ConvertFrom-Json
          $body = $json.body -split "\n"
          
          $fields = @{}
          foreach ($line in $body) {
            if ($line -match '^\*\*([^:]+):\*\*\s*(.*)$') {
              $fields[$matches[1].Trim()] = $matches[2].Trim()
            }
          }
          
          Write-Output "Season: $($fields['Season'])"
          Write-Output "Department: $($fields['Department'])"
          Write-Output "ArticleCount: $($fields['ArticleCount'])"
          Write-Output "Promotion: $($fields['promotion'])"

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "This POS API input issue has been automatically processed and closed by a GitHub Actions workflow."
