name: Close POS API Issue with Details

on:
  issues:
    types: [opened]

jobs:
  process_issue:
    runs-on: pos
    steps:
      - name: Create Issue Data File
        run: |
          echo "${{ github.event.issue.body }}" > issue_data.txt
      - name: Copy the file to local
        run: |
          copy issue_data.txt "C:\Users\MUKESH\Downloads\issue_data.txt"
      - name: Extract and Print Issue Fields using PowerShell
        shell: pwsh
        run: |
          $content = Get-Content issue_data.txt
          
          $fields = @{}
          foreach ($line in $content) {
            if ($line -match '^\*\*(.+?):\*\*\s*(.+)$') {
              $fields[$matches[1].Trim()] = $matches[2].Trim()
            }
          }
          
          Write-Output "Season: $($fields['Season'])"
          Write-Output "Department: $($fields['Department'])"
          Write-Output "ArticleCount: $($fields['ArticleCount'])"
          Write-Output "Promotion: $($fields['promotion'])"

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "This POS API input issue has been automatically processed and closed by a GitHub Actions workflow."
