name: Process User Registration

on:
  # issues:
  #   types: [opened]

jobs:
  process-user:
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue details
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          echo "Processing User Registration..."
          echo "Issue Content:"
          echo "$ISSUE_BODY"
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Username
        id: regex-match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.issue.body }}
          regex: '### Username\s+(\w+)'

      - name: Set Username
        run: echo "USERNAME=${{ steps.regex-match.outputs.group1 }}" >> $GITHUB_ENV
        
        
        #  get and set the gmail
      - name: Extract Gmail
        id: regex-match-for-gmail
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.issue.body }}
          regex: '### Gmail\s+(\w+)'

      - name: Set Gmail
        run: echo "GMAIL=${{ steps.regex-match-for-gmail.outputs.group1 }}" >> $GITHUB_ENV
      
      #  get and set the Gender
      - name: Extract Gender
        id: regex-match-gender
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.issue.body }}
          regex: 'Gender\s+- (Male|Female)'

      - name: Set gender
        run: echo "GENDER=${{ steps.regex-match-gender.group1 }}" >> $GITHUB_ENV

      - name: Extract Above 18 Confirmation
        id: regex-match-above-18
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.issue.body }}
          regex: 'Are you above 18\?\s+- \[ \] Yes, I confirm that I am above 18.'
      - name: Set Above 18 Confirmation
        run: echo "ABOVE_18=${{ steps.regex-match-above-18.outputs.group0 }}" >> $GITHUB_ENV
      # - name: Extract Inputs
      #   id: extract
      #   run: |
      #     USERNAME=$(echo "${{ github.event.issue.body }}" | awk -F'\n' '/### Username/{getline; print}' | xargs)
      #     GMAIL=$(echo "${{ github.event.issue.body }}" | awk -F'\n' '/### Gmail/{getline; print}' | xargs)
      #     ABOVE_18=$(echo "${{ github.event.issue.body }}" | grep -q "Yes, I confirm that I am above 18." && echo "Yes" || echo "No")
      #     GENDER=$(echo "${{ github.event.issue.body }}" | awk -F'\n' '/### Select your gender/{getline; print}' | xargs)

      #     echo "Extracted Values:"
      #     echo "Username: $USERNAME"
      #     echo "Gmail: $GMAIL"
      #     echo "Above 18: $ABOVE_18"
      #     echo "Gender: $GENDER"

      #     echo "USERNAME=$USERNAME" >> $GITHUB_ENV
      #     echo "GMAIL=$GMAIL" >> $GITHUB_ENV
      #     echo "ABOVE_18=$ABOVE_18" >> $GITHUB_ENV
      #     echo "GENDER=$GENDER" >> $GITHUB_ENV
          
      - name: Close the Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            ✅ User Registration processed successfully.

            **Username:** ${{ env.USERNAME }}  
            **Gmail:** ${{ env.GMAIL }}  
            **Above 18:** ${{ env.ABOVE_18 }}  
            **Gender:** ${{ env.GENDER }}  
            
            Closing this issue.
