on:
  workflow_dispatch:
    inputs:
      PromotionRequired:
        description: 'Promotion required or not'
        type: boolean
        required: true

      Countries:
        description: 'To check the options'
        type: choice
        options:
        - Sweden
        - Denmark
        - UK
        - US
jobs:
  log-the-inputs:
    runs-on: TestRunnerGithub
    steps:
    - run: |
        echo "PromtionRequired : ${{ github.event.inputs.PromotionRequired }}"
        echo "Countries: ${{ github.event.inputs.Countries }} "

